title: Seascape Ecology Lab Homepage
page-top-title: Seascape Ecology Lab
top-section-bg-text: Oregon State University Seascape Ecology Lab
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; OSU Seascape Ecology Lab 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/kegeorge98/sel.osu.github.io
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Seascape Ecology Lab
    href: '#page-top' # Default to '#<id>' if not specified
  - id: getting-started
    nav: Getting Started
    title: Getting Started
    icon: bi-file-text-fill
  - id: grad-resources
    nav: Grad Student Resources
    title: Grad Student Resources
    icon: bi-award-fill
  - id: undergrad-resources
    nav: Undergraduate Student Resources
    title: Undergraduate Student Resources
    icon: 
  - id: training-resources
    nav: Training Resources
    title: Training Resources
    icon:
  - id: data-standards
    nav: Metadata & Data Standards
    title: Metadata & Data Standards
    icon:
  - id: instrument-sops
    nav: SOPs - Instrumentation
    title: Instrumentation SOPs
    icon:
  - id: process-sops
    nav: SOPs - Processes
    title: Process SOPs
    icon:
  - id: templates
    nav: Templates
    title: Templates
    icon:
